name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
          apt-get update && apt-get install -y rsync git

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Antora project
        run: |
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/ 
          npx antora local-antora-playbook.yml --fetch

      # Uploads the generated site
      - uses: actions/upload-artifact@v3
        with:
          name: cicd-232cf038086dc798e51d5201bba9945277562851
          path: docs/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        if: contains(github.ref,'refs/heads/main')
        with:
          branch: gh-pages
          folder: cicd-232cf038086dc798e51d5201bba9945277562851
          clean: true
