name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Antora project
        run: |
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/ 
          npx antora local-antora-playbook.yml --fetch
      # Uploads the generated site
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: cicd-232cf038086dc798e51d5201bba9945277562851
