name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        if: contains(github.ref,'refs/heads/main')
        with:
          branch: gh-pages
          folder: cicd-232cf038086dc798e51d5201bba9945277562851
          clean: true
